# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calculadora_pb2 as calculadora__pb2


class CalculadoraStub(object):
    """Definicao do servico: quais RPCs ele oferece
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Calcular = channel.unary_unary(
                '/calculadora.Calculadora/Calcular',
                request_serializer=calculadora__pb2.RequisicaoCalculo.SerializeToString,
                response_deserializer=calculadora__pb2.RespostaCalculo.FromString,
                )
        self.VerificarSaude = channel.unary_unary(
                '/calculadora.Calculadora/VerificarSaude',
                request_serializer=calculadora__pb2.RequisicaoSaude.SerializeToString,
                response_deserializer=calculadora__pb2.RespostaSaude.FromString,
                )


class CalculadoraServicer(object):
    """Definicao do servico: quais RPCs ele oferece
    """

    def Calcular(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerificarSaude(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculadoraServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Calcular': grpc.unary_unary_rpc_method_handler(
                    servicer.Calcular,
                    request_deserializer=calculadora__pb2.RequisicaoCalculo.FromString,
                    response_serializer=calculadora__pb2.RespostaCalculo.SerializeToString,
            ),
            'VerificarSaude': grpc.unary_unary_rpc_method_handler(
                    servicer.VerificarSaude,
                    request_deserializer=calculadora__pb2.RequisicaoSaude.FromString,
                    response_serializer=calculadora__pb2.RespostaSaude.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculadora.Calculadora', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calculadora(object):
    """Definicao do servico: quais RPCs ele oferece
    """

    @staticmethod
    def Calcular(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculadora.Calculadora/Calcular',
            calculadora__pb2.RequisicaoCalculo.SerializeToString,
            calculadora__pb2.RespostaCalculo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerificarSaude(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculadora.Calculadora/VerificarSaude',
            calculadora__pb2.RequisicaoSaude.SerializeToString,
            calculadora__pb2.RespostaSaude.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
