# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculadora.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61lculadora.proto\x12\x0b\x63\x61lculadora\";\n\x11RequisicaoCalculo\x12\x10\n\x08operacao\x18\x01 \x01(\t\x12\t\n\x01\x61\x18\x02 \x01(\x01\x12\t\n\x01\x62\x18\x03 \x01(\x01\"7\n\x0fRespostaCalculo\x12\x11\n\tresultado\x18\x01 \x01(\x01\x12\x11\n\tdescricao\x18\x02 \x01(\t\"\x11\n\x0fRequisicaoSaude\"/\n\rRespostaSaude\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06versao\x18\x02 \x01(\t2\xa3\x01\n\x0b\x43\x61lculadora\x12H\n\x08\x43\x61lcular\x12\x1e.calculadora.RequisicaoCalculo\x1a\x1c.calculadora.RespostaCalculo\x12J\n\x0eVerificarSaude\x12\x1c.calculadora.RequisicaoSaude\x1a\x1a.calculadora.RespostaSaudeb\x06proto3')



_REQUISICAOCALCULO = DESCRIPTOR.message_types_by_name['RequisicaoCalculo']
_RESPOSTACALCULO = DESCRIPTOR.message_types_by_name['RespostaCalculo']
_REQUISICAOSAUDE = DESCRIPTOR.message_types_by_name['RequisicaoSaude']
_RESPOSTASAUDE = DESCRIPTOR.message_types_by_name['RespostaSaude']
RequisicaoCalculo = _reflection.GeneratedProtocolMessageType('RequisicaoCalculo', (_message.Message,), {
  'DESCRIPTOR' : _REQUISICAOCALCULO,
  '__module__' : 'calculadora_pb2'
  # @@protoc_insertion_point(class_scope:calculadora.RequisicaoCalculo)
  })
_sym_db.RegisterMessage(RequisicaoCalculo)

RespostaCalculo = _reflection.GeneratedProtocolMessageType('RespostaCalculo', (_message.Message,), {
  'DESCRIPTOR' : _RESPOSTACALCULO,
  '__module__' : 'calculadora_pb2'
  # @@protoc_insertion_point(class_scope:calculadora.RespostaCalculo)
  })
_sym_db.RegisterMessage(RespostaCalculo)

RequisicaoSaude = _reflection.GeneratedProtocolMessageType('RequisicaoSaude', (_message.Message,), {
  'DESCRIPTOR' : _REQUISICAOSAUDE,
  '__module__' : 'calculadora_pb2'
  # @@protoc_insertion_point(class_scope:calculadora.RequisicaoSaude)
  })
_sym_db.RegisterMessage(RequisicaoSaude)

RespostaSaude = _reflection.GeneratedProtocolMessageType('RespostaSaude', (_message.Message,), {
  'DESCRIPTOR' : _RESPOSTASAUDE,
  '__module__' : 'calculadora_pb2'
  # @@protoc_insertion_point(class_scope:calculadora.RespostaSaude)
  })
_sym_db.RegisterMessage(RespostaSaude)

_CALCULADORA = DESCRIPTOR.services_by_name['Calculadora']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUISICAOCALCULO._serialized_start=34
  _REQUISICAOCALCULO._serialized_end=93
  _RESPOSTACALCULO._serialized_start=95
  _RESPOSTACALCULO._serialized_end=150
  _REQUISICAOSAUDE._serialized_start=152
  _REQUISICAOSAUDE._serialized_end=169
  _RESPOSTASAUDE._serialized_start=171
  _RESPOSTASAUDE._serialized_end=218
  _CALCULADORA._serialized_start=221
  _CALCULADORA._serialized_end=384
# @@protoc_insertion_point(module_scope)
